# Create a  bridge network "inception" for all containers to communicate with each other
# Create local volumes for wordpress and mariadb services
# SERVICES: Nginx, Wordpress, MariaDB, reddis, adminer, ftp server
# Volumes: wordpress, mariadb
# Networks: inception
# Ports: 443, 3306, 8080, 21, 20, 12000
# Images will be built from the Dockerfile in ./requiremenmts/%service_name% directory
# Add healthcheck for all services
# Add restart unless-stopped policy for all services
# Forward environment variables to the services, these will be public data for easier configuration (Domain name etc...,) credentials will be stored in docker secrets
# Each service will have a shared and individual configuration file

### ### ### ### ### ### ###
### Docker-compose.yaml ###
### ### ### ### ### ### ###

version: '3.8'

#################################################
#~~~~~~~SERVICES
#################################################
#################################################


services:

  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    restart: "unless-stopped"
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception
    env_file: .env
    healthcheck:
      test: ["CMD-SHELL", "find /tmp/healthcheck -mmin -1"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 15s

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    depends_on:
      mariadb:
        condition: service_healthy
    restart: "unless-stopped"
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    env_file:
      - .env

  nginx:
    build:
      context: ./requirements/nginx
      args:
        - OPEN_SSL_SUBJ=${OPEN_SSL_SUBJ}
    container_name: nginx
    depends_on:
      wordpress:
        condition: service_started
      bonus_site:
        condition: service_started
      nginx_scraper:
        condition: service_started
    volumes:
      - wordpress:/var/www/wordpress
    restart: "unless-stopped"
    ports:
      - "443:443"
    networks:
      - inception
    healthcheck:
      test: ["CMD-SHELL", "ping -c 1 localhost"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 30s

  redis:
    build: ./requirements/bonus/redis
    container_name: redis
    depends_on:
      - wordpress
    restart: "unless-stopped"
    ports:
      - "6379:6379"
    networks:
      - inception
    env_file:
      - .env

  bonus_site:
    build:
      context: ./requirements/bonus/bonus_site
      args:
        - OPEN_SSL_SUBJ=${OPEN_SSL_SUBJ}
    container_name: bonus_site
    volumes:
      - bonus_site:/var/www/site
    restart: "unless-stopped"
    ports:
      - "4343"
    networks:
      - inception
    env_file:
      - .env

  adminer:
    build: ./requirements/bonus/adminer
    container_name: adminer
    depends_on:
      mariadb:
        condition: service_healthy
    restart: "unless-stopped"
    ports:
      - "3133:3133" # Link to external port for remote db management
    networks:
      - inception
    env_file:
      - .env

  ftp:
    build:
      context: ./requirements/bonus/ftp
      args:
        - OPEN_SSL_SUBJ=${OPEN_SSL_SUBJ}
        - FTP_USER_PASSWORD=${FTP_USER_PASSWORD}
    container_name: ftp
    restart: "unless-stopped"
    volumes:
      - wordpress:/var/www/wordpress
    ports:
      - "20:20" # Active mode, for server response
      - "21:21" # FTP port, for client communication
      - "21000-21010:21000-21010" # Passive mode, range of ports outside of the default range
    networks:
      - inception
    env_file:
      - .env

  prometheus:
    build: ./requirements/bonus/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    networks:
      - inception
    restart: "unless-stopped"
    volumes:
      - prometheus:/prometheus

  nginx_scraper:
    build: ./requirements/bonus/nginx_scraper
    container_name: nginx_scraper
    restart: "unless-stopped"
    networks:
      - inception
    ports:
      - "4242:4242"

#################################################
#~~~~~~~VOLUMES
#################################################
#################################################

volumes:
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      device: /home/myos/data/wordpress
      o: bind
      type: none

  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      device: /home/myos/data/mariadb
      o: bind
      type: none

  bonus_site:
    name: bonus_site
    driver: local
    driver_opts:
      device: /home/myos/data/bonus_site
      o: bind
      type: none

  # Technically not a requirement, but still useful to keep the data long term
  prometheus:
    name: prometheus
    driver: local
    driver_opts:
      device: /home/myos/data/prometheus
      o: bind
      type: none


#################################################
#~~~~~~~Network
#################################################
#################################################

networks:
  inception:
    name: inception
    driver: bridge