FROM alpine:3.18

EXPOSE 4343

ARG OPEN_SSL_SUBJ

### Get the latest packages
RUN apk update && apk upgrade

### Install the necessary packages
RUN apk add --no-cache nginx
RUN apk add --no-cache openssl
RUN apk add --no-cache bash
RUN apk add --no-cache openrc

RUN openrc
RUN touch /run/openrc/softlevel

### Create the necessary directories
RUN mkdir -p /run/nginx
RUN mkdir -p /var/nginx/ssl
RUN mkdir -p /var/www/site

COPY ./conf/nginx.conf /etc/nginx/nginx.conf
COPY ./conf/err404.html /var/www/site/err404.html
COPY ./conf/err404.css /var/www/site/err404.css
COPY ./conf/index.html /var/www/site/index.html
COPY ./conf/style.css /var/www/site/style.css

RUN openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
	-keyout /var/nginx/ssl/nginx.key \
	-out /var/nginx/ssl/nginx.crt \
	-subj ${OPEN_SSL_SUBJ} 2> /dev/null

RUN chown -R nginx:nginx /var/www/site && chmod -R 764 /var/www/site
RUN chown -R nginx:nginx /var/nginx && chmod -R 764 /var/nginx
RUN chown -R nginx:nginx /var/lib/nginx && chmod -R 764 /var/lib/nginx
RUN chown -R nginx:nginx /var/log/nginx /etc/nginx /usr/share/nginx
RUN chown -R nginx:nginx /run/nginx/ && chmod -R 764 /run/nginx/
USER nginx


CMD ["nginx", "-g", "daemon off;"]
