FROM alpine:3.18

EXPOSE 443

ARG OPEN_SSL_SUBJ

### Get the latest packages
RUN apk update && apk upgrade

### Install the necessary packages
RUN apk add --no-cache nginx
RUN apk add --no-cache openssl
RUN apk add --no-cache bash
RUN apk add --no-cache openrc

RUN openrc
RUN touch /run/openrc/softlevel

### Create the necessary directories
RUN mkdir -p /run/nginx/
RUN mkdir -p /var/nginx/ssl/
RUN mkdir -p /var/www/html/
RUN mkdir -p /var/www/wordpress/

COPY ./conf/nginx.conf /etc/nginx/nginx.conf
COPY ./conf/fck.html /var/www/html/fck.html

RUN openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
	-keyout /var/nginx/ssl/nginx.key \
	-out /var/nginx/ssl/nginx.crt \
	-subj ${OPEN_SSL_SUBJ}

RUN adduser -D -G 'www-data' "www-data"
RUN chown -R www-data:www-data /var/www && chmod 760 /var/www
RUN chown -R www-data:www-data /var/nginx && chmod 760 /var/nginx
RUN chown -R www-data:www-data /var/lib/nginx && chmod 760 /var/lib/nginx
RUN chown -R www-data:www-data /var/log/nginx /etc/nginx /usr/share/nginx
RUN chown -R www-data:www-data /run/nginx/ && chmod 760 /run/nginx/
USER www-data


CMD ["nginx", "-g", "daemon off;"]
